### ISSUE TITLE
`complog create` doesn't work with absolute paths

### ISSUE THREAD

**Issue by Youssef1313** [jaredpar/basic-compiler-logger#1]
![image](https://user-images.githubusercontent.com/31348972/192980086-1c953e32-11cd-45e3-86d4-beb36bf57427.png)

This makes it harder to get a log from CI when I want to do something like this:

```yml
  - bash: |
      dotnet tool install --global Basic.CompilerLog
      complog create --projectName=Uno.UI $(build.artifactstagingdirectory)\build-$(GitVersion.FullSemVer)-$(XAML_FLAVOR_BUILD).binlog
    condition: always()
```

A workaround for this issue is:

```yml
  - task: CmdLine@2
    inputs:
      workingDirectory: $(build.artifactstagingdirectory)
      script: |
        dotnet tool install --global Basic.CompilerLog
        complog create --projectName=Uno.UI build-$(GitVersion.FullSemVer)-$(XAML_FLAVOR_BUILD).binlog
    condition: always()
```
